#!/bin/bash 
set -e

source $(dirname $0)/../../functions

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

name=linux
#version=4.19.19
version=5.4.6

fetch "https://mirrors.tuna.tsinghua.edu.cn/kernel/v4.x/linux-$version.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$name-$version

	make INSTALL_HDR_PATH=dest headers_install
	find dest/include \( -name .install -o -name ..install.cmd \) -delete
	cp -rv dest/include/* /usr/include
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" >> /usr/scrip_linux-api-headers || exit $PIPESTATUS

rm -fr $TMP
