#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
source $(dirname $0)/../../pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=kbd
version=2.2.0
 
fetch "https://www.kernel.org/pub/linux/utils/$name/$name-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
	sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

	PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr --disable-vlock

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

