#!/bin/bash

LFS="/mnt/lfs"
umount ${LFS}/proc ${LFS}/dev ${LFS}/sys &> /dev/null

mount -o bind /proc ${LFS}/proc
mount -o bind /dev ${LFS}/dev
mount -o bind /sys ${LFS}/sys

#chroot --userspec=1000:999 "$LFS" /tools/bin/env -i \
chroot --userspec=1000:999 "$LFS" /usr/bin/env -i \
     HOME=/home/ben     \
     TERM="$TERM"       \
     PS1='$? \u:\w \$ ' \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
     /bin/bash --login +h

#     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
#     /tools/bin/bash --login +h

#     PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/tools/sbin \
#     /tools/bin/bash --login +h

umount ${LFS}/proc ${LFS}/dev ${LFS}/sys &> /dev/null

