#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
source $(dirname $0)/../../pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=gawk
version=5.0.1
 
fetch "https://ftp.gnu.org/gnu/$name/$name-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	# ensure some unneeded files are not installed
	sed -i 's/extras//' Makefile.in

	./configure --prefix=/usr                          \
		    --disable-nls

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

