#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=pacman
version=5.0.2
 
fetch "https://sources.archlinux.org/other/pacman/pacman-5.0.2.tar.gz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

#        ./configure --prefix=/usr \
#        	    --disable-doc     \
#	            --disable-shared  \
#        	    --sysconfdir=/etc \
#	            --localstatedir=/var

	  ./configure --prefix=/usr --sysconfdir=/etc \
	    --localstatedir=/var --enable-doc \
	    --with-scriptlet-shell=/usr/bin/bash \
	    --with-ldconfig=/usr/bin/ldconfig
	  make
	  make -C contrib

        make install

        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

