#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
source $(dirname $0)/../../pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=intltool
version=0.51.0
 
fetch "http://launchpad.net/intltool/trunk/$version/+download/$name-$version.tar.gz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version
	
	sed -i 's:\\\${:\\\$\\{:' intltool-update.in

	./configure --prefix=/usr                          \

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

