#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
source $(dirname $0)/../../pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=procps-ng
version=3.3.15
 
fetch "https://sourceforge.net/projects/procps-ng/files/Production/$name-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure --prefix=/usr                          \
	            --exec-prefix=                           \
	            --libdir=/usr/lib                        \
        	    --docdir=/usr/share/doc/procps-ng-3.3.15 \
	            --disable-static                         \
        	    --disable-kill                           \


#	            --with-systemd

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

