#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=pkgconfig
version=1.6.3
 
fetch "https://github.com/pkgconf/pkgconf/archive/$name-$version.tar.gz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure \
	    --prefix=/usr \
	    --sysconfdir=/etc \
	    --with-pkg-config-dir=/usr/lib/pkgconfig:/usr/share/pkgconfig \
	    --with-system-libdir=/usr/lib \
	    --with-system-includedir=/usr/include \
	    --disable-static

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

