#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=grep
version=3.4
 
fetch "https://ftp.gnu.org/gnu/$name/$name-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure --prefix=/usr                          \
		    --bindir=/bin --disable-nls

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

# description	: Programs for searching through files
# homepage	: https://www.gnu.org/software/grep/
# maintainer	: emmett1, emmett1.2miligrams at gmail.com
# depends	: pcre

name=grep
version=3.4
release=1
source="https://ftp.gnu.org/gnu/$name/$name-$version.tar.xz"

build() {
	cd $name-$version

	./configure --prefix=/usr --bindir=/bin --disable-nls
	make
	make DESTDIR=$PKG install
}
