#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=flex
version=2.6.4
 
fetch " https://github.com/westes/flex/releases/download/v$version/$name-$version.tar.gz " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	sed -i "/math.h/a #include <malloc.h>" src/flexdef.h
	
	HELP2MAN=/tools/bin/true \
	./configure --prefix=/usr                          \
		    --disable-nls

        make
	make install

	ln -sv flex /usr/bin/lex

        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

