#!/bin/bash -e

source $(dirname $0)/functions

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

name=file
version=5.38

fetch " ftp://ftp.astron.com/pub/$name/$name-$version.tar.gz " $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$name-$version

	mkdir -v build
	cd       build
	
	../configure --prefix=/tools            \
		     --prefix=/cross-tools \
		     --disable-static

	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
