#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=glibc
VERSION=${GLIBC_VER}

fetch "https://mirrors.tuna.tsinghua.edu.cn/gnu/glibc/glibc-$GLIBC_VER.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	mkdir -v build
	cd       build
	
	../configure                             \
		  --prefix=/tools                    \
		  --host=$LFS_TGT                    \
		  --build=$LFS_BLD		     \
		  --disable-multilib		     \
		  --disable-nls   		     \
		  --enable-kernel=3.2                \
	          --with-headers=/tools/include      \
		  libc_cv_forced_unwind=yes	     \
		  libc_cv_c_cleanup=yes		     \
		  --with-abi=64 		     \
		  --with-endlan=little

	make
	make install
	
	echo 'int main(){}' > dummy.c
	$LFS_TGT-gcc dummy.c
	readelf -l a.out | grep ': /tools'
	rm -v dummy.c a.out
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
