#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=gcc
VERSION=${GCC_VER}

fetch "http://ftp.lfs-matrix.net/pub/lfs/lfs-packages/7.7-systemd/mpfr-3.1.2.tar.xz " $SRC
fetch "http://ftp.lfs-matrix.net/pub/lfs/lfs-packages/7.7-systemd/mpc-1.0.2.tar.gz " $SRC
fetch "http://ftp.lfs-matrix.net/pub/lfs/lfs-packages/7.7-systemd/gmp-6.0.0a.tar.xz" $SRC
fetch "http://ftp.lfs-matrix.net/pub/lfs/lfs-packages/7.7-systemd/gcc-4.9.2.tar.bz2" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP
tar -xf $SRC/mpfr-$MPFR_VER.tar.xz -C $TMP/$NAME-$VERSION
tar -xf $SRC/gmp-${GMP_VER}a.tar.xz -C $TMP/$NAME-$VERSION
tar -xf $SRC/mpc-$MPC_VER.tar.gz -C $TMP/$NAME-$VERSION

{ time \
   {

	cd $TMP/$NAME-$VERSION

	cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
		`dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h
		
	for file in gcc/config/{linux,i386/linux{,64}}.h
	do
	  cp -uv $file{,.orig}
	  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
		  -e 's@/usr@/tools@g' $file.orig > $file
	  echo '
	#undef STANDARD_STARTFILE_PREFIX_1
	#undef STANDARD_STARTFILE_PREFIX_2
	#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
	#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
	  touch $file.orig
	done

	case $(uname -m) in
	  x86_64)
	    sed -e '/m64=/s/lib64/lib/' \
		-i.orig gcc/config/i386/t-linux64
	  ;;
	esac

	mv -v mpfr-$MPFR_VER mpfr
	mv -v gmp-$GMP_VER gmp
	mv -v mpc-$MPC_VER mpc

	sed -e '1161 s|^|//|' \
	    -i libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc

	mkdir -v build
	cd       build
	
	CC=$LFS_TGT-gcc                                    \
	CXX=$LFS_TGT-g++                                   \
	AR=$LFS_TGT-ar                                     \
	RANLIB=$LFS_TGT-ranlib                             \
	../configure                                       \
		--prefix=/tools                                \
		--with-local-prefix=/tools                     \
		--with-native-system-header-dir=/tools/include \
		--enable-languages=c,c++                       \
		--disable-libstdcxx-pch                        \
		--disable-multilib                             \
		--disable-bootstrap                            \
		--disable-libgomp
	make
	make install
	ln -sv gcc /tools/bin/cc
	
	echo 'int main(){}' > dummy.c
	cc dummy.c
	readelf -l a.out | grep ': /tools'
	rm -v dummy.c a.out
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
