#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/functions
source $(dirname $0)/pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=libcap
version=${LIBCAP_VER}
 
fetch "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/$name-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	sed -i '/install.*STALIBNAME/d' libcap/Makefile
	make RAISE_SETFCAP=no \
	     BUILD_GPERF=no \
	     KERNEL_HEADERS=/tools/include \
	     PAM_CAP=no
	make RAISE_SETFCAP=no lib=lib \
	     BUILD_GPERF=no \
	     KERNEL_HEADERS=/tools/include \
	     PAM_CAP=no \
	     prefix=/tools install

        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP	
	
