#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/functions
source $(dirname $0)/pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=libarchive
version=${LIBARCHIVE_VER}
 
fetch "https://libarchive.org/downloads/${name}-${version}.tar.xz " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure --prefix=/tools \
		    --without-xml2 \
		    --disable-shared
	
	make
	make install

        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP	
	
