#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/functions
source $(dirname $0)/pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=pacman
version=${PACMAN_VER}
 
fetch "https://sources.archlinux.org/other/pacman/${name}-${version}.tar.gz  " $SRC

 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	LIBARCHIVE_CFLAGS="-I/tools/include" \
                   LIBARCHIVE_LIBS="-L/tools/lib -larchive" \
                   NETTLE_CFLAGS="-I/tools/include" \
                   NETTLE_LIBS="-L/tools/lib -lnettle" \
                   ./configure --prefix=/tools/ --sysconfdir=/etc/local/ \
                   --localstatedir=/var --disable-doc --with-crypto=nettle --disable-static
	make
	make DESTDIR=${PWD}/DESTDIR install
	cp -rv DESTDIR/tools/* /tools/
#
#
#	./configure --prefix=/tools   \
#        	    --disable-doc     \
#	            --disable-shared  \
#        	    --sysconfdir=/etc \
#	            --localstatedir=/var
#	make
#	make install

	
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP	
	
