#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=XML-Parser
version=2.46
 
fetch "http://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-$version.tar.gz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version
	
	perl Makefile.PL

        make
	make install
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_perl-xml-parser || exit $PIPESTATUS

rm -fr $TMP	
	
