#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=Python
version=3.8.2
 
fetch "https://www.python.org/ftp/python/$version/Python-$version.tar.xz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure --prefix=/usr       \
	            --enable-shared     \
	            --with-system-expat \
	            --with-system-ffi   \
                    --with-ensurepip=yes 

        make
	make install

	chmod -v 755 /usr/lib/libpython3.8.so
	chmod -v 755 /usr/lib/libpython3.so
	ln -sfv pip3.8 /usr/bin/pip3
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_python3 || exit $PIPESTATUS

rm -fr $TMP	
	

