#!/bin/bash 
set -e

PKG=(
linux-api-headers
man-pages
glibc
adjusting-the-toolchain
zlib
bzip2
pkg-config
libcap
file
readline
m4
bc
binutils
gmp
mpfr
mpc
attr
acl
shadow
gcc
pkg-config
ncurses
libcap
sed
psmisc
bison
flex
grep
bash
libtool
gdbm
gperf
expat
perl
perl-xml-parser
autoconf
automake
xz
kmod
gettext
elfutils
libffi
openssl
python3
ninja
meson
coreutils
diffutils
gawk
findutils
groff
less
gzip
zstd
iproute2
kbd
libpipeline
make
patch
man-db
tar
texinfo
vim
#systemd
dbus
procps-ng
util-linux
e2fsprogs
git
)
SCRIPTDIR=$(dirname $0)/rootscripts/core/

#source $SCRIPTDIR/functions
source rootscripts/functions

for script in ${PKG[@]}; do
	if [ "$1" = "fetch" ]; then
		SRC=/var/cache/scratchpkg/sources $SCRIPTDIR$script/spkgbuild "$1"
	elif [ -f /usr/"scrip_$script" ]; then
		echo "--- $script skipped ---"
	else
		echo "*** $script ***"
		SRC=/var/cache/scratchpkg/sources $SCRIPTDIR$script/spkgbuild
		echo; echo "*** $script done ***"; echo
#		[ "$1" = $(echo $script | cut -d - -f1) ] && exit
	fi
done

[ "$1" = "fetch" ] && exit 0

#sudo chown -Rv 0:0 $LFS

echo
echo "**************************************************"
echo "*********    Toolchain build complete    *********"
echo "**************************************************"
