#!/bin/bash 
set -e

PKG=(
libarchive
fakeroot
pacman
wget
curl
httpup
)
SCRIPTDIR=$(dirname $0)/rootscripts/core/

#source $SCRIPTDIR/functions
source rootscripts/functions

for script in ${PKG[@]}; do
	if [ "$1" = "fetch" ]; then
		SRC=/var/cache/scratchpkg/sources $SCRIPTDIR$script/spkgbuild "$1"
	elif [ -f /usr/"scrip_$script" ]; then
		echo "--- $script skipped ---"
	else
		echo "*** $script ***"
		SRC=/var/cache/scratchpkg/sources $SCRIPTDIR$script/spkgbuild
		echo; echo "*** $script done ***"; echo
#		[ "$1" = $(echo $script | cut -d - -f1) ] && exit
	fi
done

[ "$1" = "fetch" ] && exit 0

#sudo chown -Rv 0:0 $LFS

echo
echo "**************************************************"
echo "*********    Toolchain build complete    *********"
echo "**************************************************"
