#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=attr
version=2.4.48
 
fetch " https://download.savannah.gnu.org/releases/$name/$name-$version.tar.gz" $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	./configure --prefix=/usr \
	            --bindir=/bin \
	            --disable-static \
            	    --sysconfdir=/etc \
		    --disable-nls
	make
	make install

	#mv -v /usr/lib/libattr.so.* /lib
	#ln -sfv ../../lib/$(readlink $PKG/usr/lib/libattr.so) /usr/lib/libattr.so
        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

