#!/bin/bash 
set -e
set -x
 
source $(dirname $0)/../../functions
source $(dirname $0)/../../pkgversion
 
filename=$(echo $0 | rev | cut -d / -f1 | rev)
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
 
name=ncurses
version=6.2
 
fetch "https://ftp.gnu.org/gnu//$name/$name-$version.tar.gz  " $SRC
 
[ "$1" = "fetch" ] && exit 0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC
 
tar xf $SRC/$tarballname -C $TMP
 
{ time \
   {
 
        cd $TMP/$name-$version

	sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in

	./configure --prefix=/usr \
	            --mandir=/usr/share/man \
	            --with-shared \
	            --without-debug \
	            --without-normal \
	            --enable-pc-files \
	            --enable-widec
	make
	make install

	#mv -v $PKG/usr/lib/libncursesw.so.6* $PKG/lib
	#ln -sfv ../../lib/$(readlink $PKG/usr/lib/libncursesw.so) $PKG/usr/lib/libncursesw.so

	for lib in ncurses form panel menu ; do
	    rm -vf                    /usr/lib/lib${lib}.so
	    echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
	    ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc
	done

	rm -vf                     /usr/lib/libcursesw.so
	echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so
	ln -sfv libncurses.so      /usr/lib/libcurses.so

        }   
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > /usr/scrip_$name || exit $PIPESTATUS

rm -fr $TMP	
	

